== Dockerfile for Arch Linux with Packages and AUR Package Manager

This Dockerfile creates an image for Arch Linux with a set of pre-installed packages, including Git, lf, Zsh, Zsh autosuggestion, trash-cli, htop, lsd, procs, fzf, bat, and Auracle and Yay package manager configured.

=== How to Use

To build the Docker image, use the following command in the same directory as the Dockerfile:


[source, sh]
docker build -t cosmic .

To run a container with the built image, use the following command:

[source, sh]
sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock cosmic:latest


NOTE: By default, the container will log in as the admin user, and the default working directory will be the user's home directory.

=== What's Included

The following packages are pre-installed in the Docker image:

- `Git` - version control system for software development
- `lf` - terminal file manager
- `Zsh` - shell with advanced features
- `Zsh autosuggestion` - intelligent suggestions for Zsh
- `trash-cli` - command-line interface to the freedesktop.org trashcan
- `htop` - interactive process viewer for Unix
- `lsd` - modern replacement for ls
- `procs` - modern replacement for ps
- `fzf` - command-line fuzzy finder
- `bat` - cat clone with syntax highlighting and Git integration
- `Auracle` - lightweight Aur helper
- `Yay` - Yet Another Yogurt - an AUR Helper written in Go

=== Contributing

If you would like to contribute to this project, please fork the repository and create a pull request with your changes.


